ALTER TABLE "PlatformConfig" ADD COLUMN IF NOT EXISTS "playerReturnPct" DECIMAL(6,2) NOT NULL DEFAULT 100;
ALTER TABLE "PlatformConfig" ADD COLUMN IF NOT EXISTS "engagementEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "PlatformConfig" ADD COLUMN IF NOT EXISTS "engagementHookGames" INTEGER NOT NULL DEFAULT 5;
ALTER TABLE "PlatformConfig" ADD COLUMN IF NOT EXISTS "engagementHookPct" DECIMAL(6,2) NOT NULL DEFAULT 120;
ALTER TABLE "PlatformConfig" ADD COLUMN IF NOT EXISTS "engagementTightPct" DECIMAL(6,2) NOT NULL DEFAULT 20;

ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "playerReturnPct" DECIMAL(6,2);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "engagementMode" TEXT NOT NULL DEFAULT 'off';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "gamesPlayed" INTEGER NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS "Event" (
    "id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "multiplier" DECIMAL(8,2) NOT NULL DEFAULT 1.5,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "startsAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "endsAt" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Event_pkey" PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "Event_active_idx" ON "Event"("active");
CREATE INDEX IF NOT EXISTS "Event_endsAt_idx" ON "Event"("endsAt");
