-- CPF unique when present
CREATE UNIQUE INDEX IF NOT EXISTS "User_cpf_key" ON "User"("cpf") WHERE "cpf" IS NOT NULL;

ALTER TABLE "PlatformConfig" ADD COLUMN IF NOT EXISTS "winRatePct" DECIMAL(6,2) NOT NULL DEFAULT 50;
ALTER TABLE "PlatformConfig" ADD COLUMN IF NOT EXISTS "housePool" DECIMAL(18,2) NOT NULL DEFAULT 0;
ALTER TABLE "PlatformConfig" ADD COLUMN IF NOT EXISTS "ownerEmail" TEXT;

ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "cpfVerified" BOOLEAN NOT NULL DEFAULT false;
