ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "cpf" TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS "User_cpf_key" ON "User"("cpf") WHERE "cpf" IS NOT NULL;

ALTER TABLE "WithdrawalRequest" ADD COLUMN IF NOT EXISTS "cpf" TEXT;
ALTER TABLE "WithdrawalRequest" ADD COLUMN IF NOT EXISTS "pixKey" TEXT;
ALTER TABLE "WithdrawalRequest" ADD COLUMN IF NOT EXISTS "fullName" TEXT;

ALTER TABLE "PlatformConfig" ADD COLUMN IF NOT EXISTS "returnCap" DECIMAL(10,4) NOT NULL DEFAULT 2.0;
